#ifndef SYNTHESIS_CONSTANTS_H
#define SYNTHESIS_CONSTANTS_H

#define VERSION_STR "0.1"
#define VERSION_MAJOR 0
#define VERSION_MINOR 1
#define VERSION_DATE_STR "2018-10-25"

#define NUM_INPUTS 2

#define SUCCESS 0
#define FAILURE 1

#endif
